name: Deploy Infra (Bicep)

on:
  workflow_dispatch:
  push:
    paths:
      - 'infra/bicep/**'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy Bicep to Resource Group
        uses: azure/cli@v2
        with:
          inlineScript: |
            az group create -n ${{ vars.AZ_RG }} -l ${{ vars.AZ_LOCATION }}
            az deployment group create               --resource-group ${{ vars.AZ_RG }}               --template-file infra/bicep/main.bicep               --parameters prefix=${{ vars.PREFIX }} location=${{ vars.AZ_LOCATION }}
