name: Deploy Policies

on:
  workflow_dispatch:
  push:
    paths:
      - 'policy/**'

permissions:
  id-token: write
  contents: read

jobs:
  policies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Create custom policy definitions
        uses: azure/cli@v2
        with:
          inlineScript: |
            az policy definition create --name deny-public-storage --mode All               --display-name "Deny public network access for Storage Accounts"               --rules policy/definitions/deny-public-storage.json || true

            az policy definition create --name require-private-endpoints --mode Indexed               --display-name "Require Private Endpoints for Storage"               --rules policy/definitions/require-private-endpoints.json || true

            az policy definition create --name deny-public-ip-on-vm --mode All               --display-name "Deny public IP on NICs/VMs"               --rules policy/definitions/deny-public-ip-on-vm.json || true

            az deployment sub create               --location ${{ vars.AZ_LOCATION }}               --template-file policy/assignments/sub-assignment.bicep
